# Generated by Django 4.2.6 on 2023-10-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=2000)),
                ('status', models.CharField(default='new', max_length=50)),
            ],
        ),
    ]
