# Generated by Django 4.2.6 on 2023-10-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zealthy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_query',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
